name: Sync to Maven Central
description: Syncs a release to Maven Central and waits for it to be available for use
inputs:
  jfrog-cli-config-token:
    description: 'Config token for the JFrog CLI'
    required: true
  initializr-version:
    description: 'The version of Initializr that is being synced to Central'
    required: true
  sonatype-token-name:
    description: 'Token username for the Sonatype Central Portal'
    required: true
  sonatype-token:
    description: 'Token for the Sonatype Central Portal'
    required: true
runs:
  using: composite
  steps:
    - name: Set Up JFrog CLI
      uses: jfrog/setup-jfrog-cli@2bc6e55719cd37dfb2f655a1e4f16c3440182a9f # v4.5.13
      env:
        JF_ENV_SPRING: ${{ inputs.jfrog-cli-config-token }}
    - name: Download Release Artifacts
      shell: bash
      run: jf rt download --spec ${{ format('{0}/artifacts.spec', github.action_path) }} --spec-vars 'buildName=${{ format('initializr-{0}', inputs.initializr-version) }};buildNumber=${{ github.run_number }}'
    - name: Sync
      uses: spring-io/central-publish-action@0cdd90d12e6876341e82860d951e1bcddc1e51b6 # v0.2.0
      with:
        token-name: ${{ inputs.sonatype-token-name }}
        token: ${{ inputs.sonatype-token }}
    - name: Await
      shell: bash
      run: |
        url=${{ format('https://repo.maven.apache.org/maven2/io/spring/initializr/initializr-generator/{0}/initializr-generator-{0}.jar', inputs.initializr-version) }}
        echo "Waiting for $url"
        until curl --fail --head --silent $url > /dev/null
        do
          echo "."
          sleep 60
        done
        echo "$url is available"
